host = "localhost"
pg_port = "5432"
dbname = "databae_name"
user = "my_psql_user"
password = "my_psql_password"
server_port = ":3000" # Must begin with a colon.
use_cache = false # Set to true to enable file caching.
production = false # Set to true if in production mode.
