CREATE TABLE IF NOT EXISTS users (
	id serial PRIMARY KEY,
	"name" VARCHAR (20) NOT NULL,
	username VARCHAR (20) UNIQUE NOT NULL,
	password VARCHAR (60) NOT NULL,
  admin BOOLEAN NOT NULL DEFAULT false,
  disabled BOOLEAN NOT NULL DEFAULT false,
	last_login TIMESTAMPTZ NOT NULL DEFAULT '0001-01-01 01:00:00',
	created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS landmarks (
  id serial PRIMARY KEY,
  "name" VARCHAR (255) UNIQUE NOT NULL,
  native_name VARCHAR (255) UNIQUE NOT NULL,
  "type" VARCHAR (255) NOT NULL,
  description TEXT NOT NULL,
  continent VARCHAR (255) NOT NULL,
  country VARCHAR (255) NOT NULL,
  state_city VARCHAR (255) NOT NULL,
  start_year INTEGER NOT NULL,
  end_year INTEGER NOT NULL,
  area NUMERIC NOT NULL,
	height NUMERIC NOT NULL,
  wiki_url TEXT NOT NULL,
	img_url TEXT NOT NULL,
	user_username VARCHAR(20) UNIQUE NOT NULL DEFAULT 'default',
	created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT user_username_fk
    FOREIGN KEY(user_username) 
	    REFERENCES users(username)  ON DELETE SET DEFAULT ON UPDATE CASCADE
);
